name: tabular-data-gen
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas
  - numpy
  - scikit-learn
  - seaborn
  - matplotlib
  - jupyter
  - boto3  
  - pip
  - pip:
    - tabgan
